/**
 * Live4.tv - Stream Targets
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks.   Here in this documentation, you will find a step-by-step for integrating our API.  Feel free to contact us in case you need any help.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\") 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateAndStartLiveRequest model module.
 * @module StreamNetworkApi/model/CreateAndStartLiveRequest
 * @version 1.0
 */
class CreateAndStartLiveRequest {
    /**
     * Constructs a new <code>CreateAndStartLiveRequest</code>.
     * @alias module:StreamNetworkApi/model/CreateAndStartLiveRequest
     * @param title {String} 
     * @param description {String} 
     * @param accounts {Array.<String>} An array of social network tokens to create the live stream (the value we return after the login) IMPORTANT! All tokens must be from the same user (userExternalId)
     */
    constructor(title, description, accounts) { 
        
        CreateAndStartLiveRequest.initialize(this, title, description, accounts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, description, accounts) { 
        obj['title'] = title;
        obj['description'] = description;
        obj['accounts'] = accounts;
    }

    /**
     * Constructs a <code>CreateAndStartLiveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:StreamNetworkApi/model/CreateAndStartLiveRequest} obj Optional instance to populate.
     * @return {module:StreamNetworkApi/model/CreateAndStartLiveRequest} The populated <code>CreateAndStartLiveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateAndStartLiveRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('accounts')) {
                obj['accounts'] = ApiClient.convertToType(data['accounts'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateAndStartLiveRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateAndStartLiveRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateAndStartLiveRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['accounts'])) {
            throw new Error("Expected the field `accounts` to be an array in the JSON data but got " + data['accounts']);
        }

        return true;
    }


}

CreateAndStartLiveRequest.RequiredProperties = ["title", "description", "accounts"];

/**
 * @member {String} title
 */
CreateAndStartLiveRequest.prototype['title'] = undefined;

/**
 * @member {String} description
 */
CreateAndStartLiveRequest.prototype['description'] = undefined;

/**
 * An array of social network tokens to create the live stream (the value we return after the login) IMPORTANT! All tokens must be from the same user (userExternalId)
 * @member {Array.<String>} accounts
 */
CreateAndStartLiveRequest.prototype['accounts'] = undefined;






export default CreateAndStartLiveRequest;

