/**
 * Live4.tv - Stream Targets
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks.   Here in this documentation, you will find a step-by-step for integrating our API.  Feel free to contact us in case you need any help.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\") 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CommentsResponse from './CommentsResponse';

/**
 * The GetCommentsResponse model module.
 * @module StreamNetworkApi/model/GetCommentsResponse
 * @version 1.0
 */
class GetCommentsResponse {
    /**
     * Constructs a new <code>GetCommentsResponse</code>.
     * @alias module:StreamNetworkApi/model/GetCommentsResponse
     * @param uuid {String} The live stream uuid
     * @param count {Number} The total number of comments returned
     * @param lastCommentTimestamp {Number} The timestamp of the last comment returned. You can use it for the next request.
     * @param comments {Array.<module:StreamNetworkApi/model/CommentsResponse>} An list of comments
     */
    constructor(uuid, count, lastCommentTimestamp, comments) { 
        
        GetCommentsResponse.initialize(this, uuid, count, lastCommentTimestamp, comments);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid, count, lastCommentTimestamp, comments) { 
        obj['uuid'] = uuid;
        obj['count'] = count;
        obj['lastCommentTimestamp'] = lastCommentTimestamp;
        obj['comments'] = comments;
    }

    /**
     * Constructs a <code>GetCommentsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:StreamNetworkApi/model/GetCommentsResponse} obj Optional instance to populate.
     * @return {module:StreamNetworkApi/model/GetCommentsResponse} The populated <code>GetCommentsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCommentsResponse();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('lastCommentTimestamp')) {
                obj['lastCommentTimestamp'] = ApiClient.convertToType(data['lastCommentTimestamp'], 'Number');
            }
            if (data.hasOwnProperty('comments')) {
                obj['comments'] = ApiClient.convertToType(data['comments'], [CommentsResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetCommentsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetCommentsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GetCommentsResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        if (data['comments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['comments'])) {
                throw new Error("Expected the field `comments` to be an array in the JSON data but got " + data['comments']);
            }
            // validate the optional field `comments` (array)
            for (const item of data['comments']) {
                CommentsResponse.validateJSON(item);
            };
        }

        return true;
    }


}

GetCommentsResponse.RequiredProperties = ["uuid", "count", "lastCommentTimestamp", "comments"];

/**
 * The live stream uuid
 * @member {String} uuid
 */
GetCommentsResponse.prototype['uuid'] = undefined;

/**
 * The total number of comments returned
 * @member {Number} count
 */
GetCommentsResponse.prototype['count'] = undefined;

/**
 * The timestamp of the last comment returned. You can use it for the next request.
 * @member {Number} lastCommentTimestamp
 */
GetCommentsResponse.prototype['lastCommentTimestamp'] = undefined;

/**
 * An list of comments
 * @member {Array.<module:StreamNetworkApi/model/CommentsResponse>} comments
 */
GetCommentsResponse.prototype['comments'] = undefined;






export default GetCommentsResponse;

