/**
 * Live4.tv - Stream Networks API
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks (currently Instagram).            We understand that Instagram currently restricts users from conducting live broadcasts without their official app.           However, our innovative API empowers users to go live on Instagram without relying on the app itself.        By leveraging our API, users gain access to a stream key, enabling them to seamlessly transmit their live broadcasts using popular software like OBS (Open Broadcaster Software).        This breakthrough feature provides users with the freedom to connect with their audience and share captivating live content on Instagram, all without the constraints of the official app.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\") 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SocialNetworkDetail from './SocialNetworkDetail';

/**
 * The SocialNetworkResponse model module.
 * @module StreamNetworkApi/model/SocialNetworkResponse
 * @version 1.0.0
 */
class SocialNetworkResponse {
    /**
     * Constructs a new <code>SocialNetworkResponse</code>.
     * @alias module:StreamNetworkApi/model/SocialNetworkResponse
     * @param count {Number} Number of social networks
     * @param socialNetworks {Array.<module:StreamNetworkApi/model/SocialNetworkDetail>} List of social networks
     */
    constructor(count, socialNetworks) { 
        
        SocialNetworkResponse.initialize(this, count, socialNetworks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, count, socialNetworks) { 
        obj['count'] = count;
        obj['social_networks'] = socialNetworks;
    }

    /**
     * Constructs a <code>SocialNetworkResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:StreamNetworkApi/model/SocialNetworkResponse} obj Optional instance to populate.
     * @return {module:StreamNetworkApi/model/SocialNetworkResponse} The populated <code>SocialNetworkResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SocialNetworkResponse();

            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('social_networks')) {
                obj['social_networks'] = ApiClient.convertToType(data['social_networks'], [SocialNetworkDetail]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SocialNetworkResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SocialNetworkResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SocialNetworkResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['social_networks']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['social_networks'])) {
                throw new Error("Expected the field `social_networks` to be an array in the JSON data but got " + data['social_networks']);
            }
            // validate the optional field `social_networks` (array)
            for (const item of data['social_networks']) {
                SocialNetworkDetail.validateJSON(item);
            };
        }

        return true;
    }


}

SocialNetworkResponse.RequiredProperties = ["count", "social_networks"];

/**
 * Number of social networks
 * @member {Number} count
 */
SocialNetworkResponse.prototype['count'] = undefined;

/**
 * List of social networks
 * @member {Array.<module:StreamNetworkApi/model/SocialNetworkDetail>} social_networks
 */
SocialNetworkResponse.prototype['social_networks'] = undefined;






export default SocialNetworkResponse;

