/**
 * Live4.tv - Stream Targets
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks.   Here in this documentation, you will find a step-by-step for integrating our API.  Feel free to contact us in case you need any help.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\") 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StopLiveDetailsResponse model module.
 * @module StreamNetworkApi/model/StopLiveDetailsResponse
 * @version 1.0
 */
class StopLiveDetailsResponse {
    /**
     * Constructs a new <code>StopLiveDetailsResponse</code>.
     * @alias module:StreamNetworkApi/model/StopLiveDetailsResponse
     * @param uuid {String} The unique identifier for the specific social network account stream
     * @param code {Number} The code of response, 200 for success, 401 for authentication error
     * @param message {String} The string message
     */
    constructor(uuid, code, message) { 
        
        StopLiveDetailsResponse.initialize(this, uuid, code, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid, code, message) { 
        obj['uuid'] = uuid;
        obj['code'] = code;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>StopLiveDetailsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:StreamNetworkApi/model/StopLiveDetailsResponse} obj Optional instance to populate.
     * @return {module:StreamNetworkApi/model/StopLiveDetailsResponse} The populated <code>StopLiveDetailsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StopLiveDetailsResponse();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StopLiveDetailsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StopLiveDetailsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StopLiveDetailsResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

StopLiveDetailsResponse.RequiredProperties = ["uuid", "code", "message"];

/**
 * The unique identifier for the specific social network account stream
 * @member {String} uuid
 */
StopLiveDetailsResponse.prototype['uuid'] = undefined;

/**
 * The code of response, 200 for success, 401 for authentication error
 * @member {Number} code
 */
StopLiveDetailsResponse.prototype['code'] = undefined;

/**
 * The string message
 * @member {String} message
 */
StopLiveDetailsResponse.prototype['message'] = undefined;






export default StopLiveDetailsResponse;

