/**
 * Live4.tv - Stream Networks API
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks (currently Instagram).            We understand that Instagram currently restricts users from conducting live broadcasts without their official app.           However, our innovative API empowers users to go live on Instagram without relying on the app itself.        By leveraging our API, users gain access to a stream key, enabling them to seamlessly transmit their live broadcasts using popular software like OBS (Open Broadcaster Software).        This breakthrough feature provides users with the freedom to connect with their audience and share captivating live content on Instagram, all without the constraints of the official app.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\") 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StopLiveRequest model module.
 * @module StreamNetworkApi/model/StopLiveRequest
 * @version 1.0.0
 */
class StopLiveRequest {
    /**
     * Constructs a new <code>StopLiveRequest</code>.
     * @alias module:StreamNetworkApi/model/StopLiveRequest
     * @param saveLive {Boolean} If you desire to save the live stream after it ends
     */
    constructor(saveLive) { 
        
        StopLiveRequest.initialize(this, saveLive);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, saveLive) { 
        obj['saveLive'] = saveLive || false;
    }

    /**
     * Constructs a <code>StopLiveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:StreamNetworkApi/model/StopLiveRequest} obj Optional instance to populate.
     * @return {module:StreamNetworkApi/model/StopLiveRequest} The populated <code>StopLiveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StopLiveRequest();

            if (data.hasOwnProperty('accounts')) {
                obj['accounts'] = ApiClient.convertToType(data['accounts'], ['String']);
            }
            if (data.hasOwnProperty('saveLive')) {
                obj['saveLive'] = ApiClient.convertToType(data['saveLive'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StopLiveRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StopLiveRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StopLiveRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['accounts'])) {
            throw new Error("Expected the field `accounts` to be an array in the JSON data but got " + data['accounts']);
        }

        return true;
    }


}

StopLiveRequest.RequiredProperties = ["saveLive"];

/**
 * An array of social network tokens to create the live stream (the value we return after the login) IMPORTANT! All tokens must be from the same user (userExternalId)
 * @member {Array.<String>} accounts
 */
StopLiveRequest.prototype['accounts'] = undefined;

/**
 * If you desire to save the live stream after it ends
 * @member {Boolean} saveLive
 * @default false
 */
StopLiveRequest.prototype['saveLive'] = false;






export default StopLiveRequest;

