/**
 * Live4.tv - Stream Networks API
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks (currently Instagram).            We understand that Instagram currently restricts users from conducting live broadcasts without their official app.           However, our innovative API empowers users to go live on Instagram without relying on the app itself.        By leveraging our API, users gain access to a stream key, enabling them to seamlessly transmit their live broadcasts using popular software like OBS (Open Broadcaster Software).        This breakthrough feature provides users with the freedom to connect with their audience and share captivating live content on Instagram, all without the constraints of the official app.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\") 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CommentsResponse from './model/CommentsResponse';
import CommentsResponseUser from './model/CommentsResponseUser';
import CreateAndStartLiveAccountDetailsResponse from './model/CreateAndStartLiveAccountDetailsResponse';
import CreateAndStartLiveRequest from './model/CreateAndStartLiveRequest';
import CreateAndStartLiveResponse from './model/CreateAndStartLiveResponse';
import GetAuthoriseUrlRequest from './model/GetAuthoriseUrlRequest';
import GetCommentsResponse from './model/GetCommentsResponse';
import HttpExceptionResponse from './model/HttpExceptionResponse';
import PostCommentRequest from './model/PostCommentRequest';
import PostCommentResponse from './model/PostCommentResponse';
import Redirect from './model/Redirect';
import SocialNetworkAccount from './model/SocialNetworkAccount';
import SocialNetworkDetail from './model/SocialNetworkDetail';
import SocialNetworkResponse from './model/SocialNetworkResponse';
import StartListeningToCommentsAccountDetailsResponse from './model/StartListeningToCommentsAccountDetailsResponse';
import StartListeningToCommentsRequest from './model/StartListeningToCommentsRequest';
import StartListeningToCommentsResponse from './model/StartListeningToCommentsResponse';
import StopListeningToCommentsAccountDetailsResponse from './model/StopListeningToCommentsAccountDetailsResponse';
import StopListeningToCommentsRequest from './model/StopListeningToCommentsRequest';
import StopListeningToCommentsResponse from './model/StopListeningToCommentsResponse';
import StopLiveDetailsResponse from './model/StopLiveDetailsResponse';
import StopLiveRequest from './model/StopLiveRequest';
import StopLiveResponse from './model/StopLiveResponse';
import ToggleCommentRequest from './model/ToggleCommentRequest';
import ToggleCommentResponse from './model/ToggleCommentResponse';
import ToggleCommentResponseDetails from './model/ToggleCommentResponseDetails';
import AccountsApi from './StreamNetworkApi/AccountsApi';
import CommentsApi from './StreamNetworkApi/CommentsApi';
import LiveStreamsApi from './StreamNetworkApi/LiveStreamsApi';
import SocialNetworksApi from './StreamNetworkApi/SocialNetworksApi';


/**
* Omnichannel for live streaming on social networks  We&#39;re glad that you chose to use Live4.tv&#39;s API for managing your connection with social networks (currently Instagram).            We understand that Instagram currently restricts users from conducting live broadcasts without their official app.           However, our innovative API empowers users to go live on Instagram without relying on the app itself.        By leveraging our API, users gain access to a stream key, enabling them to seamlessly transmit their live broadcasts using popular software like OBS (Open Broadcaster Software).        This breakthrough feature provides users with the freedom to connect with their audience and share captivating live content on Instagram, all without the constraints of the official app.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \&quot;Login flow image\&quot;) .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Live4tvStreamNetworksApiJavascript = require('StreamNetworkApi/index'); // See note below*.
* var xxxSvc = new Live4tvStreamNetworksApiJavascript.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Live4tvStreamNetworksApiJavascript.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['StreamNetworkApi/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Live4tvStreamNetworksApiJavascript.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Live4tvStreamNetworksApiJavascript.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module StreamNetworkApi/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:StreamNetworkApi/ApiClient}
     */
    ApiClient,

    /**
     * The CommentsResponse model constructor.
     * @property {module:StreamNetworkApi/model/CommentsResponse}
     */
    CommentsResponse,

    /**
     * The CommentsResponseUser model constructor.
     * @property {module:StreamNetworkApi/model/CommentsResponseUser}
     */
    CommentsResponseUser,

    /**
     * The CreateAndStartLiveAccountDetailsResponse model constructor.
     * @property {module:StreamNetworkApi/model/CreateAndStartLiveAccountDetailsResponse}
     */
    CreateAndStartLiveAccountDetailsResponse,

    /**
     * The CreateAndStartLiveRequest model constructor.
     * @property {module:StreamNetworkApi/model/CreateAndStartLiveRequest}
     */
    CreateAndStartLiveRequest,

    /**
     * The CreateAndStartLiveResponse model constructor.
     * @property {module:StreamNetworkApi/model/CreateAndStartLiveResponse}
     */
    CreateAndStartLiveResponse,

    /**
     * The GetAuthoriseUrlRequest model constructor.
     * @property {module:StreamNetworkApi/model/GetAuthoriseUrlRequest}
     */
    GetAuthoriseUrlRequest,

    /**
     * The GetCommentsResponse model constructor.
     * @property {module:StreamNetworkApi/model/GetCommentsResponse}
     */
    GetCommentsResponse,

    /**
     * The HttpExceptionResponse model constructor.
     * @property {module:StreamNetworkApi/model/HttpExceptionResponse}
     */
    HttpExceptionResponse,

    /**
     * The PostCommentRequest model constructor.
     * @property {module:StreamNetworkApi/model/PostCommentRequest}
     */
    PostCommentRequest,

    /**
     * The PostCommentResponse model constructor.
     * @property {module:StreamNetworkApi/model/PostCommentResponse}
     */
    PostCommentResponse,

    /**
     * The Redirect model constructor.
     * @property {module:StreamNetworkApi/model/Redirect}
     */
    Redirect,

    /**
     * The SocialNetworkAccount model constructor.
     * @property {module:StreamNetworkApi/model/SocialNetworkAccount}
     */
    SocialNetworkAccount,

    /**
     * The SocialNetworkDetail model constructor.
     * @property {module:StreamNetworkApi/model/SocialNetworkDetail}
     */
    SocialNetworkDetail,

    /**
     * The SocialNetworkResponse model constructor.
     * @property {module:StreamNetworkApi/model/SocialNetworkResponse}
     */
    SocialNetworkResponse,

    /**
     * The StartListeningToCommentsAccountDetailsResponse model constructor.
     * @property {module:StreamNetworkApi/model/StartListeningToCommentsAccountDetailsResponse}
     */
    StartListeningToCommentsAccountDetailsResponse,

    /**
     * The StartListeningToCommentsRequest model constructor.
     * @property {module:StreamNetworkApi/model/StartListeningToCommentsRequest}
     */
    StartListeningToCommentsRequest,

    /**
     * The StartListeningToCommentsResponse model constructor.
     * @property {module:StreamNetworkApi/model/StartListeningToCommentsResponse}
     */
    StartListeningToCommentsResponse,

    /**
     * The StopListeningToCommentsAccountDetailsResponse model constructor.
     * @property {module:StreamNetworkApi/model/StopListeningToCommentsAccountDetailsResponse}
     */
    StopListeningToCommentsAccountDetailsResponse,

    /**
     * The StopListeningToCommentsRequest model constructor.
     * @property {module:StreamNetworkApi/model/StopListeningToCommentsRequest}
     */
    StopListeningToCommentsRequest,

    /**
     * The StopListeningToCommentsResponse model constructor.
     * @property {module:StreamNetworkApi/model/StopListeningToCommentsResponse}
     */
    StopListeningToCommentsResponse,

    /**
     * The StopLiveDetailsResponse model constructor.
     * @property {module:StreamNetworkApi/model/StopLiveDetailsResponse}
     */
    StopLiveDetailsResponse,

    /**
     * The StopLiveRequest model constructor.
     * @property {module:StreamNetworkApi/model/StopLiveRequest}
     */
    StopLiveRequest,

    /**
     * The StopLiveResponse model constructor.
     * @property {module:StreamNetworkApi/model/StopLiveResponse}
     */
    StopLiveResponse,

    /**
     * The ToggleCommentRequest model constructor.
     * @property {module:StreamNetworkApi/model/ToggleCommentRequest}
     */
    ToggleCommentRequest,

    /**
     * The ToggleCommentResponse model constructor.
     * @property {module:StreamNetworkApi/model/ToggleCommentResponse}
     */
    ToggleCommentResponse,

    /**
     * The ToggleCommentResponseDetails model constructor.
     * @property {module:StreamNetworkApi/model/ToggleCommentResponseDetails}
     */
    ToggleCommentResponseDetails,

    /**
    * The AccountsApi service constructor.
    * @property {module:StreamNetworkApi/StreamNetworkApi/AccountsApi}
    */
    AccountsApi,

    /**
    * The CommentsApi service constructor.
    * @property {module:StreamNetworkApi/StreamNetworkApi/CommentsApi}
    */
    CommentsApi,

    /**
    * The LiveStreamsApi service constructor.
    * @property {module:StreamNetworkApi/StreamNetworkApi/LiveStreamsApi}
    */
    LiveStreamsApi,

    /**
    * The SocialNetworksApi service constructor.
    * @property {module:StreamNetworkApi/StreamNetworkApi/SocialNetworksApi}
    */
    SocialNetworksApi
};
