/**
 * Live4.tv - Stream Targets
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks.   Here in this documentation, you will find a step-by-step for integrating our API.  Feel free to contact us in case you need any help.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\") 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SocialNetworkResponse from '../model/SocialNetworkResponse';

/**
* SocialNetworks service.
* @module StreamNetworkApi/StreamNetworkApi/SocialNetworksApi
* @version 1.0
*/
export default class SocialNetworksApi {

    /**
    * Constructs a new SocialNetworksApi. 
    * @alias module:StreamNetworkApi/StreamNetworkApi/SocialNetworksApi
    * @class
    * @param {module:StreamNetworkApi/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:StreamNetworkApi/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the socialNetworkControllerGetAllActive operation.
     * @callback module:StreamNetworkApi/StreamNetworkApi/SocialNetworksApi~socialNetworkControllerGetAllActiveCallback
     * @param {String} error Error message, if any.
     * @param {module:StreamNetworkApi/model/SocialNetworkResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all social network integrations available
     * @param {String} xApiKey 
     * @param {module:StreamNetworkApi/StreamNetworkApi/SocialNetworksApi~socialNetworkControllerGetAllActiveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:StreamNetworkApi/model/SocialNetworkResponse}
     */
    socialNetworkControllerGetAllActive(xApiKey, callback) {
      let postBody = null;
      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling socialNetworkControllerGetAllActive");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'x-api-key': xApiKey
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SocialNetworkResponse;
      return this.apiClient.callApi(
        '/api/v1/social-networks', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
